name: Generate Datas

on:
  schedule: # execte every 12 hours
    - cron: "* */12 * * *"
  worflow_dispath:

jobs:
  # Snake animation
  - uses: Platane/snk@master
  id: snake-gif
  with:
    github_user_name: santosalexandreclaudio
    svg_out_path: dist/github-contritbuition-grid-snake.svg

  - uses: crazy-max/ghaction-github-pages@v2.1.3
  with:
    target_branch: output
    build_dir: dist
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
